### PR TITLE
Support GHC 9.6.3

### LINKED ISSUE #5: Fails to build with GHC 9.6.3
Hi @ddssff,

when building `haskell-unixutils` 1.54.2 on GHC 9.6.3, the following error occurs:
```
Configuring Unixutils-1.54.2...
Preprocessing library for Unixutils-1.54.2..
Building library for Unixutils-1.54.2..
[1 of 9] Compiling System.Unix.Chroot ( System/Unix/Chroot.hs, dist/build/System/Unix/Chroot.dyn_o )

System/Unix/Chroot.hs:48:27: error: [GHC-83865]
    • Couldn't match expected type: OpenFileFlags
                                    -> IO System.Posix.Types.Fd
                  with actual type: IO System.Posix.Types.Fd
    • The function ‘openFd’ is applied to four value arguments,
        but its type ‘FilePath
                      -> OpenMode -> OpenFileFlags -> IO System.Posix.Types.Fd’
        has only three
      In the second argument of ‘($)’, namely
        ‘openFd "/" ReadOnly Nothing defaultFileFlags’
      In a stmt of a 'do' block:
        rootFd <- liftIO $ openFd "/" ReadOnly Nothing defaultFileFlags
   |
48 |        rootFd <- liftIO $ openFd "/" ReadOnly Nothing defaultFileFlags
   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

System/Unix/Chroot.hs:48:47: error: [GHC-83865]
    • Couldn't match expected type ‘OpenFileFlags’
                  with actual type ‘Maybe a0’
    • In the third argument of ‘openFd’, namely ‘Nothing’
      In the second argument of ‘($)’, namely
        ‘openFd "/" ReadOnly Nothing defaultFileFlags’
      In a stmt of a 'do' block:
        rootFd <- liftIO $ openFd "/" ReadOnly Nothing defaultFileFlags
   |
48 |        rootFd <- liftIO $ openFd "/" ReadOnly Nothing defaultFileFlags
   |                                               ^^^^^^^
[2 of 9] Compiling System.Unix.Crypt ( System/Unix/Crypt.hs, dist/build/System/Unix/Crypt.dyn_o )
[3 of 9] Compiling System.Unix.Directory ( System/Unix/Directory.hs, dist/build/System/Unix/Directory.dyn_o )
[4 of 9] Compiling System.Unix.FilePath ( dist/build/System/Unix/FilePath.hs, dist/build/System/Unix/FilePath.dyn_o )
[5 of 9] Compiling System.Unix.Files ( System/Unix/Files.hs, dist/build/System/Unix/Files.dyn_o )
[6 of 9] Compiling System.Unix.KillByCwd ( System/Unix/KillByCwd.hs, dist/build/System/Unix/KillByCwd.dyn_o )
[7 of 9] Compiling System.Unix.Misc ( System/Unix/Misc.hs, dist/build/System/Unix/Misc.dyn_o )
[8 of 9] Compiling System.Unix.Mount ( System/Unix/Mount.hs, dist/build/System/Unix/Mount.dyn_o )
[9 of 9] Compiling System.Unix.SpecialDevice ( System/Unix/SpecialDevice.hs, dist/build/System/Unix/SpecialDevice.dyn_o )
```

There seems to be a change in  `openFd` such that the `Nothing` becomes redundant.

### System information
OS: Arch Linux
Linux: 6.6.6.arch1-1
GHC: 9.6.3
base: 4.18.1.0
unixutils: 1.54.2

### PR DESCRIPTION
**Pull request by Vekhir**
Fixes #5

### CODE REVIEW

**Comment by ddssff** [comment]
Could you find the version of base where this change was made?  We should add
```
#if MIN_VERSION_base(4,12,0)  (or whatever)
<new code>
#else
<old code>
#endif
```

**Comment by Vekhir** [comment]
Of course. It's not in `base` though, but in `unix`: https://hackage.haskell.org/package/unix-2.8.0.0/docs/System-Posix-IO.html#v:openFd
`unix 2.8.0.0` is the first release with that change, the preceding `unix 2.7.3` has the old behaviour.

**Comment by Vekhir** [comment]
@ddssff Added the macro to only use the fix when on unix 2.8.0 or higher

**Comment by ddssff** [comment]
Nicely done!

**Comment by Vekhir** [comment]
Thanks! Are you making a hackage release for this?

**Comment by ddssff** [comment]
Oh, I can if it helps.  I wasn't sure anyone was actually using this package.

**Comment by ddssff** [comment]
Version 1.54.3 uploaded to hackage.

**Comment by Vekhir** [comment]
Thanks. It's in the Arch repos, and a hackage release makes it easier to update.
I guess it's an orphan dependency that was once used for something else and just forgotten about.

**Comment by Vekhir** [comment]
@ddssff Can you confirm that 1.54.3 is on Hackage? I know that it can take a while to get public, but after 2 days, it still shows only 1.54.2...

**Comment by ddssff** [comment]
Sorry about that, there was a hackage error that I thought was a warning.

**Comment by Vekhir** [comment]
Now it works. Thanks once again!
